security:

    providers:
        our_db_provider:
            entity:
                class: App\Entity\Participant
                property: username

    firewalls:
        main:
            remember_me:
                secret:   '%kernel.secret%'
                path:     /
            pattern: ^/
            provider: our_db_provider
            anonymous: ~
            form_login:
                login_path: login
                check_path: login

            logout:
                path: logout
                target: home

    encoders:
        App\Entity\Participant:
            algorithm: 'bcrypt'

    access_control:
            - { path: ^/admin, roles: ROLE_ADMIN }
            - { path: ^/sortie, roles: IS_AUTHENTICATED_REMEMBERED }
            - { path: ^/participant, roles: IS_AUTHENTICATED_REMEMBERED }
            - { path: ^/lieu, roles: IS_AUTHENTICATED_REMEMBERED }
